import type { Metadata } from 'next'; import Link from 'next/link';
export const metadata: Metadata = { title: 'How to Use Your Phone as a Speedometer', description: 'Step-by-step guide to using your smartphone as a GPS speedometer. Learn the best apps, browser tools, and tips for accurate phone-based speed tracking.', alternates: { canonical: '/guides/phone-as-speedometer' } };
export default function Page() { return (
<article className="py-12 md:py-16"><div className="container-main max-w-3xl">
<nav className="text-xs mb-6" aria-label="Breadcrumb" style={{ color: 'var(--text-tertiary)' }}><Link href="/" className="no-underline hover:underline" style={{ color: 'var(--text-tertiary)' }}>Home</Link><span className="mx-2">›</span><Link href="/guides" className="no-underline hover:underline" style={{ color: 'var(--text-tertiary)' }}>Guides</Link><span className="mx-2">›</span><span style={{ color: 'var(--text-secondary)' }}>Phone as Speedometer</span></nav>
<header className="mb-10"><p className="text-sm font-semibold uppercase tracking-widest mb-3" style={{ color: 'var(--brand-primary)' }}>Guide</p><h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-4" style={{ color: 'var(--text-primary)' }}>How to Use Your Phone as a Speedometer</h1><p className="text-lg leading-relaxed" style={{ color: 'var(--text-secondary)' }}>Your smartphone has a GPS chip that can measure speed just like a dedicated GPS device. Here&apos;s how to use it safely and effectively.</p></header>
<div className="space-y-8" style={{ color: 'var(--text-secondary)' }}>
<div className="rounded-xl p-5" style={{ backgroundColor: 'rgba(0,212,170,0.06)', border: '1px solid rgba(0,212,170,0.15)' }}><p className="font-semibold mb-1 text-sm" style={{ color: 'var(--brand-primary)' }}>Quick Answer</p><p className="text-sm leading-relaxed">Open a browser-based GPS speedometer (like ours), grant location permission, and you&apos;ll see your speed instantly. No app download needed. For the best experience, mount your phone securely and use outdoors.</p></div>
<section><h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>Step-by-Step Guide</h2>
<ol className="list-decimal pl-5 space-y-4 text-sm leading-relaxed">
<li><strong>Open the speedometer</strong> — Visit our <Link href="/speedometer" className="underline" style={{ color: 'var(--brand-primary)' }}>GPS Speedometer</Link> page on your phone&apos;s browser (Chrome on Android, Safari on iPhone).</li>
<li><strong>Grant location permission</strong> — When prompted, tap &quot;Allow&quot; to give the browser access to your GPS. This is required for speed measurement.</li>
<li><strong>Enable high-accuracy location</strong> — On Android: Settings → Location → Mode → High accuracy. On iPhone: Settings → Privacy → Location Services → On.</li>
<li><strong>Mount your phone</strong> — Use a dashboard or windshield mount. Never hold your phone while driving. Safety first.</li>
<li><strong>Tap Start</strong> — The speedometer will begin displaying your real-time speed. Wait 10–30 seconds for GPS to lock on for best accuracy.</li>
<li><strong>Choose your unit</strong> — Switch between km/h, mph, knots, or m/s depending on your needs.</li>
</ol></section>
<section><h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>Web Browser vs Native App</h2>
<div className="rounded-xl overflow-hidden border" style={{ borderColor: 'var(--border-primary)' }}><table className="w-full text-sm"><thead><tr style={{ backgroundColor: 'var(--bg-tertiary)' }}><th className="px-4 py-3 text-left font-semibold" style={{ color: 'var(--text-primary)' }}>Feature</th><th className="px-4 py-3 text-left font-semibold" style={{ color: 'var(--text-primary)' }}>Browser Speedometer</th><th className="px-4 py-3 text-left font-semibold" style={{ color: 'var(--text-primary)' }}>Native App</th></tr></thead><tbody>
{[['Installation', 'None — instant use', 'Download required'],['Storage', 'None', '10–100 MB'],['Speed accuracy', 'Good (±1-2 km/h)', 'Good (±1-2 km/h)'],['Background tracking', 'No (page must be visible)', 'Yes'],['Screen wake', 'Supported (most browsers)', 'Yes'],['Offline use', 'Partial (page must load first)', 'Full offline']].map(([f, b, n], i) => (
<tr key={f} style={{ borderTop: '1px solid var(--border-primary)', backgroundColor: i % 2 === 0 ? 'var(--bg-card)' : 'var(--bg-secondary)' }}><td className="px-4 py-2.5 font-medium" style={{ color: 'var(--text-primary)' }}>{f}</td><td className="px-4 py-2.5">{b}</td><td className="px-4 py-2.5">{n}</td></tr>
))}
</tbody></table></div></section>
<section><h2 className="text-xl font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>Safety Tips</h2>
<ul className="list-disc pl-5 space-y-2 text-sm leading-relaxed"><li><strong>Always mount your phone</strong> — never hold it while driving</li><li><strong>Set up before driving</strong> — open the speedometer and start tracking before you begin your journey</li><li><strong>Don&apos;t rely solely on GPS speed</strong> — your vehicle&apos;s speedometer is the legally recognized instrument</li><li><strong>Charge your phone</strong> — GPS usage drains battery faster than normal use</li><li><strong>Be aware of local laws</strong> — some jurisdictions restrict phone mounting or screen use while driving</li></ul></section>
<div className="rounded-xl p-6 text-center" style={{ backgroundColor: 'var(--bg-secondary)' }}><h3 className="font-semibold mb-2" style={{ color: 'var(--text-primary)' }}>Try It Now</h3><p className="text-sm mb-4" style={{ color: 'var(--text-secondary)' }}>Turn your phone into a speedometer right now — free, no download required.</p><Link href="/speedometer" className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm no-underline" style={{ backgroundColor: 'var(--brand-primary)', color: '#000' }}>Open GPS Speedometer →</Link></div>
<div className="pt-6" style={{ borderTop: '1px solid var(--border-primary)' }}><h3 className="font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>Related Guides</h3><div className="flex flex-wrap gap-2"><Link href="/guides/how-gps-speed-works" className="px-4 py-2 rounded-lg text-sm font-medium no-underline" style={{ backgroundColor: 'var(--bg-tertiary)', color: 'var(--text-secondary)' }}>How GPS Speed Works</Link><Link href="/guides/how-accurate-is-gps-speed" className="px-4 py-2 rounded-lg text-sm font-medium no-underline" style={{ backgroundColor: 'var(--bg-tertiary)', color: 'var(--text-secondary)' }}>GPS Speed Accuracy</Link></div></div>
</div></div></article>); }
